/**
 * Created by sourabh on 9/5/17.
 */

export const CREATE_POST_STARTED="CREATE_POST_STARTED";
export const CREATE_POST_SUCCESS="CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE="CREATE_POST_FAILURE";

export const FETCH_USER_STARTED="FETCH_USER_STARTED";
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE="FETCH_USER_FAILURE";


export const FETCH_POST_STARTED="FETCH_POST_STARTED";
export const FETCH_POST_SUCCESS="FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE="FETCH_POST_FAILURE";



export const CREATE_LIKE_DISLIKE_STARTED="CREATE_LIKE_DISLIKE_STARTED";
export const CREATE_LIKE_DISLIKE_SUCCESS="CREATE_LIKE_DISLIKE_SUCCESS";
export const CREATE_LIKE_DISLIKE_FAILURE="CREATE_LIKE_DISLIKE_FAILURE";


export const FETCH_LKES_DISLIKES_STARTED="FETCH_LIKES_DISLIKES_STARTED";
export const FETCH_LIKES_DISLIKES_SUCCESS="FETCH_LIKES_DISLIKES_SUCCESS";
export const FETCH_LIKES_DISLIKES_FAILURE="FETCH_LIKES_DISLIKES_FAILURE";


export const CREATE_COMMENT_STARTED="CREATE_COMMENT_STARTED";
export const CREATE_COMMENT_SUCCESS="CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE="CREATE_COMMENT_FAILURE";


export const FETCH_COMMENTS_STARTED="FETCH_COMMENTS_STARTED";
export const FETCH_COMMENTS_SUCCESS="FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE="FETCH_COMMENTS_FAILURE";

