/**
 * Created by sourabh on 9/5/17.
 */

export const CREATE_POST_STARTED="CREATE_POST_STARTED"
export const CREATE_POST_SUCCESS="CREATE_POST_SUCCESS"
export const CREATE_POST_FAILURE="CREATE_POST_FAILURE"

export const FETCH_USER_STARTED="FETCH_USER_STARTED"
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE="FETCH_USER_FAILURE"


export const FETCH_POST_STARTED="FETCH_POST_STARTED"
export const FETCH_POST_SUCCESS="FETCH_POST_SUCCESS"
export const FETCH_POST_FAILURE="FETCH_POST_FAILURE"